### ISSUE TITLE
ASVO query page UI improvements (a list)

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/manta-ray-client#16]
There are a number of UI issues with the ASVO query page which I'll list here.

1. The project ID has to be selected from a list, rather than being free form.
2. The project ID drop down menu is not sorted.
3. Duration to/from doesn't seem to be a useful selection criteria for searching
4. The table that is returned includes values which cannot be searched against using the form. For example Creator/Description would be really handy to search against.
5. It would be nice to have a flag in the search to only return non-embargoed data (see issue #15 )
6. When a search is run, it would be nice to have the corresponding ADQL populated so that the query can be "saved" for later, and so that users can more easily learn how to create queries.

**Comment by gsleap** [comment]
Hi Paul thanks for all of this feedback!
1- This is fixed in the next release of the website, which is awaiting deployment.
2- This is fixed in the next release of the website, which is awaiting deployment.
3- We may remove this if we need more room for more useful options, but we may as well leave it there for now
4- Agreed- it would be good to have more search options
5- This is also a good idea
6- Also, a fantastic idea!

**Comment by harrisonbarlow** [comment]
Closing this issue as much of this has already been addressed

Point 6 is handled by a related issue in the asvo code
