### ISSUE TITLE
SSL certificates problem

### ISSUE THREAD

**Issue by lao19881213** [MWATelescope/manta-ray-client#24]
Hi Greg,
I want to download MWA raw data from ASVO.
But when I run 'mwa_client -c snapshot_list.csv -d ./' on my machine terminal, it print a ssl certificates error:
_ssl.c:334: No root certificates specified for verification of other-side certificates.

How to fix it?

Thanks,
Baoqiang

**Comment by gsleap** [comment]
Hi Baoqiang,

Have not seen this one before!

Could you please check:

  *   You are using the latest version of the code (i.e. do a git pull of the repo). Then run “python setup.py install” again if your version was out of date (actually do this anyway to ensure you have built the latest version).
  *   Check your operating system is up to date
  *   Check that your computer clock is synchronised to a time source so your computer date/time is accurate.

If none of that works, could you please reply with some info:

  *   Python version you are running
  *   Operating system and version you are using
  *   Copy and paste the output of “pip freeze” from within your virtual environment

Thanks

Greg

**Comment by lao19881213** [comment]
Hi Gerg,
Still did't works.

* Yes, I use the latest version. I get the code using this command: git clone https://github.com/ICRAR/manta-ray-client.git
* My machine's operation system is CentOS Linux release 7.4.1708 . I think this version is up to date.
* Yes, the date/time is accurate.

Python version is Python 2.7.6 .
pip freeze output as follows:

AegeanTools===1.9.7-58-g02454c8
APLpy==1.1.1
asn1crypto==0.24.0
asteval==0.9.12
astropy==2.0.7
atomicwrites==1.1.5
attrs==18.1.0
backports.functools-lru-cache==1.5
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
boto3==1.7.83
botocore==1.10.83
bottle==0.12.13
certifi==2018.8.13
cffi==1.11.5
chardet==3.0.4
colorama==0.4.1
configobj==5.0.6
crc32c==1.4
cryptography==2.3.1
cycler==0.10.0
d2to1==0.2.12.post1
daliuge==0.4.0
decorator==4.3.0
docker==3.5.0
docker-pycreds==0.3.0
docutils==0.14
enum-compat==0.0.2
enum34==1.1.6
ephem==3.7.6.0
ez-setup==0.9
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
gevent==1.3.6
greenlet==0.4.14
h5py==2.8.0
healpy==1.8.1
idna==2.7
ipaddress==1.0.22
jmespath==0.9.3
kiwisolver==1.0.1
lmfit==0.9.11
lockfile==0.12.2
mantaray-client==0.2.2
matplotlib==1.1.0
matplotlib-venn==0.11.5
metis==0.2a4
more-itertools==4.2.0
msgpack-python==0.5.6
mwapy===v1.1.0-103-g7763af8
netifaces==0.10.7
networkx==2.1
numpy==1.15.1
oskarpy==0.1.0
paramiko==2.4.1
pluggy==0.6.0
psutil==5.4.7
py==1.5.4
pyasn1==0.4.4
pycparser==2.18
pyfits==3.0.4
PyNaCl==1.2.1
pyparsing==2.2.0
pyswarm==0.6
pytest==3.6.3
python-daemon==2.2.0
python-dateutil==2.7.3
pytz==2018.5
pywcs===1.10-4.7
pywcsgrid2==0.1b2
pyzmq==17.1.2
requests==2.19.1
s3transfer==0.1.13
scipy==1.1.0
scp==0.11.0
six==1.11.0
stsci.distutils==0.3.7
subprocess32==3.5.2
uncertainties==3.0.2
urllib3==1.23
virtualenv==15.2.0
websocket-client==0.51.0
zeroconf==0.19.1
zerorpc==0.6.1

Thanks,
Baoqiang

**Comment by lao19881213** [comment]
Hi Greg,
The problem has been fixed.
I use anaconda2 as the python environment and re-install your code, then it works now.
Thanks.
Baoqiang

**Comment by lao19881213** [comment]
Hi Greg,
But there have a new error when the data size reach 2GB :
There were errors:
('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))

How to fix this new problem?

Thanks,
Baoqiang

**Comment by gsleap** [comment]
Hi Baoqiang,

Can you try to download the dataset via wget instead of the mwa_client?

To do this, open a terminal and run:
wget URL -O filename.zip

where:
URL is the url of the file to download, which you can get from your “Data Jobs” page on the MWA ASVO website.

Let me know how that goes.

Thanks

Greg

**Comment by lao19881213** [comment]
Hi Greg,
I submit a job and get the URL form MWA ASVO.
Then I use wget URL to download the file, but terminal print Bad Request:
_[1] 171969
[blao@master 1061219072]$ --2018-12-09 12:18:36--  https://asvo.mwatelescope.org:8778/api/download?job_id=80343
Resolving asvo.mwatelescope.org (asvo.mwatelescope.org)... 146.118.87.252
Connecting to asvo.mwatelescope.org (asvo.mwatelescope.org)|146.118.87.252|:8778... connected.
HTTP request sent, awaiting response... 400 Bad Request
2018-12-09 12:18:38 ERROR 400: Bad Request._

Why?

Thanks,
Baoqiang

**Comment by lao19881213** [comment]
I found the problem and it has been fixed.
The download command should be in this format:
wget "https://asvo.mwatelescope.org:8778/api/download?job_id=JJJJ&file_name=NNNNNNNNNN_ms.zip" -O my_obs.zip

Thank you very much!

Baoqiang

**Comment by gsleap** [comment]
Hi,

Sorry about that- yes, you are correct about the format. Can you please let me know if you were able to download the data ok this way?

Thanks

Greg

**Comment by lao19881213** [comment]
Hi Greg,
This way is not all smoothly, the terminal print 'Read error' when the data size reach 5%: 
2018-12-09 12:46:47 (2.76 MB/s) - Read error at byte 2283962368/45081158467 (Connection reset by peer).

I think this is the network problem, right?

Thanks,
Baoqiang

**Comment by gsleap** [comment]
Hi Baoqiang,

I was able to download the whole file yesterday to my home computer. It was slow due to my limited home internet connection, but it did not time out or abort during the several hour long transfer. So, yes, I think there is a network problem, but these things can be hard to identify.

I was wondering, where are you running the download from? Also, is it possible for you to try to download it from somewhere else? It is possible there is a problem between your computer and the server, here in Perth. Do you have any issues downloading big files (other than the MWA ASVO?)

Cheers

Greg

**Comment by lao19881213** [comment]
Hi Greg,
Sorry for the late reply.
I running the data download in China. I have try several times, but still not work. 
The data size reach 5%, print errors in terminal:
Read error at byte 2283962368/45081158467 (Connection reset by peer).

How to fix this problem?

And if I want to download all of observation data in one day, how to download in batches?

Thanks,
Baoqiang

**Comment by gsleap** [comment]
Hi Baoqiang,


Sorry that this is not working for you. I suspect the reason is that we perform transfers over an SSL encrypted connection. I think that SSL connections to China are being terminated before all of the data has transferred.


I will work on a non-SSL solution once I am back from holidays in the second week of January, as today is my last day at work until then.


If you require some data more urgently, let me know what you require and once I am back I can get it for you and provide it to you via FTP until we can solve the SSL issue.

I hope this is ok?

Cheers

Greg

________________________________

**Comment by lao19881213** [comment]
Hi Greg,
Thanks.
Have a good holiday!
Merry Christmas!


I think this is a good way for me via FTP download MWA data, I need the raw data of GLEAM year 1 (G0008) from UTC 25/08/2013 to UTC 18/06/2014 , these will be need much more storage and time.
After you back to work, you can provide to me in multiple times, a small portion of it each time. 

What do you think?

Cheers,
Baoqiang

**Comment by gsleap** [comment]
Modified server to use "http" (not https) for the actual download of files. Baoqiang confirms this now allows a complete download without a connection reset. Closing issue.
